### ISSUE TITLE
Widevine playback issue

### ISSUE THREAD

**Issue by drauggres** [NetrisTV/ti.exoplayer#3]
Module failed to play videos under `Widevine DASH Policy Tests (GTS)` from demo playlis.
```
09-24 16:01:11.589 12039-12039/com.mymymusic.mobile.qadev E/EventLogger: internalError [10.88, drmSessionManagerError]
  java.lang.IllegalArgumentException: method POST must have a request body.
    at com.android.okhttp.Request$Builder.method(Request.java:259)
    at com.android.okhttp.internal.huc.JavaApiConverter.createOkResponseForCacheGet(JavaApiConverter.java:212)
    at com.android.okhttp.internal.huc.CacheAdapter.get(CacheAdapter.java:51)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:207)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:423)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
    at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
    at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
    at com.google.android.exoplayer2.util.Util.toByteArray(Util.java:124)
    at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executePost(HttpMediaDrmCallback.java:145)
    at com.google.android.exoplayer2.drm.HttpMediaDrmCallback.executeKeyRequest(HttpMediaDrmCallback.java:130)
    at com.google.android.exoplayer2.drm.DefaultDrmSession$PostRequestHandler.handleMessage(DefaultDrmSession.java:528)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by drauggres** [comment]
Caused by bug in the SDK.
Fixed in `master` branch https://github.com/appcelerator/titanium_mobile/pull/10447
